### ISSUE TITLE
Question: Ignoring iframes

### ISSUE THREAD

**Issue by sir-captainmorgan21** [dequelabs/axe-webdriverjs#106]
If I wanted to ignore an iframe, how would I do that. We are using Google's reCaptchav3, and the Iframe it puts on our app breaks our accessibility tests. Without using reCaptchaV3, the tests pass perfectly. Have you guys tested axe on a site that uses Google's reCaptchaV3?

**Comment by AdnoC** [comment]
You can use [the `exclude` function](https://github.com/dequelabs/axe-webdriverjs/blob/develop/lib/index.js#L37) to exclude things from being tested. Note that it can take an array of selectors to select within an iframe ([docs here](https://github.com/dequelabs/axe-core/blob/develop/doc/API.md#include-exclude-object)).

That helpful?

**Comment by straker** [comment]
Closing issue since we haven't gotten a response. Please open a new issue if this is still a problem.
