### ISSUE TITLE
Make axe-core a peer dependency

### ISSUE THREAD

**Issue by liron-navon** [dequelabs/axe-webdriverjs#119]
I'm using axe-webdriverjs for automated e2e tests, but I also use the axe-chrome extension - each comes with a different version of axe-core which produces different errors.

axe-webdriverjs uses axe-core **3.3** (^3.1.2)
axe chrome extention uses axe **3.2**

It would be great if axe-core would have been a peer dependency so I could give it the same version as I have in other axe tools.

**Comment by stephenmathieson** [comment]
Making axe-core a peer dependency here would break the "most common" usage of this package and would require a major version bump. I do not think this should happen right now.

Instead, you can provide your own copy of [axe-core to the `AxeBuilder` constructor](https://github.com/dequelabs/axe-webdriverjs/blob/develop/lib/index.js#L9-L15). This looks something like:

```js
var fs = require('fs')
var AxeBuilder = require('axe-webdriverjs')
var WebDriver = require('selenium-webdriver');

var axeSource = fs.readFileSync('./path/to/your/axe.js', 'utf-8')

var driver = new WebDriver.Builder()
  .forBrowser('firefox')
  .build();

var axe = new AxeBuilder(driver, axeSource)
axe.analyze(...)
```
