### ISSUE TITLE
Nightwatch.js and aXe integration

### ISSUE THREAD

**Issue by qzqzzz** [dequelabs/axe-webdriverjs#12]
I'm using Nightwatch.js (http://nightwatchjs.org) for my e2e tests, which is something similar with selenium-webdriver (https://www.npmjs.com/package/selenium-webdriver).

As far as I can see in the aXe & Selenium Webdriver integration sample https://github.com/marcysutton/axe-webdriverjs-demo/blob/master/spec/test.js, you basically just need to call `AxeBuilder(driver).analyze(function(results) { ... })` and you get your audit results.

I guess the problem with Nightwatch.js and aXe is that Nightwatch.js' API is different from the Selenium Webdriver hence aXe does not know how to inject the iFrame in the page in order to run the audit.

Are there any plans to support this type of integration? Is there any integration example for Nightwatch.js and aXe?

**Comment by dylanb** [comment]
@cosminnicula we currently do not have plans however, you could still use axe-core with Nightwatch.js by doing the injection yourself.

**Comment by bjankord** [comment]
@cosmin-nicula If your are interested in using axe in nightwatch, you might check out these projects:

https://github.com/ahmadnassri/nightwatch-accessibility
https://github.com/snugbear/nightwatch-axe

**Comment by mgifford** [comment]
Just providing this followup https://www.previousnext.com.au/blog/automate-your-drupal-accessibility-testing-axe-and-nightwatchjs

**Comment by straker** [comment]
Closing this since Nightwatch.js released their own integration.

**Comment by mgifford** [comment]
Bloody Nightwatch community is too active....  Can you point me to the project were they did this?  https://github.com/nightwatchjs is too general.

**Comment by straker** [comment]
Isn't https://github.com/ahmadnassri/nightwatch-accessibility was the integration for Nightwatch.js and axe?

**Comment by mgifford** [comment]
I hadn't stumbled across this.  Thanks for the link.
