### ISSUE TITLE
Need to update axe-core version

### ISSUE THREAD

**Issue by kristina-hager** [dequelabs/axe-webdriverjs#159]
The present version of this code packages axe-core 3.4: https://github.com/dequelabs/axe-webdriverjs/blob/develop/package.json#L93

Can the bundled version be updated to the latest axe-core 4.0.x?

Thanks!

**Comment by straker** [comment]
Thanks for issue. So we're actually deprecating this repository soon and have moved it to [axe-core-npm](https://github.com/dequelabs/axe-core-npm/tree/develop/packages/webdriverjs) where the version of axe-core has been updated.

**Comment by kristina-hager** [comment]
Thanks! I just noticed the readme notice 👍
