### ISSUE TITLE
Violations are not reported when the target is a frameset

### ISSUE THREAD

**Issue by rodolfolanda** [dequelabs/axe-webdriverjs#16]
Hi @dylanb, @marcysutton,

I am using aXe plugin for Firefox and axe-webdriverjs to test the same pages. I get different results reported from both, in the same page:

**Firefox Plugin: 6 violations found:**
- Checkbox inputs with the same name attribute value must be part of a group....(2)
- Elements must have sufficient color contrast .......(3)
- All non-empty td element in table larger that 3 by 3 must have an associated table header....(1)

**axe-webdriver: 3 violations found:**
- Elements must have sufficient color contrast .......(3)

**Elements not found by axe-webdriver have the following target:**
- Target:#ctl_2,html > **frameset** > frame:nth-of-type(2),#z_e > tbody > tr:nth-of-type(2) > .d_gact > .d_gact > tbody > tr > .d_gs > .d_chb.float_l
- Target:#ctl_2,html > **frameset** > frame:nth-of-type(2),#z_e

**Note:** In pages without "frameset" I get the same number of violations reported from both.

Thanks,

Rodolfo Landa

**Comment by dylanb** [comment]
@rodolfolanda is the page public or can you upload an example set of files?

**Comment by rodolfolanda** [comment]
Hi @dylanb,

Can I send you the file to an email?

**Comment by dylanb** [comment]
@rodolfolanda yes, my email address is in my profile

**Comment by rodolfolanda** [comment]
@dylanb I sent you further information via email.

**Comment by rodolfolanda** [comment]
@dylanb Is there any further information that I can send to you?

**Comment by dylanb** [comment]
@rodolfolanda yes there is, please check your email

**Comment by marcysutton** [comment]
@rodolfolanda @dylanb can we get more information to resolve this issue? I'm going to close it for now, but we can reopen if the issue persists.
