### ISSUE TITLE
Is it possible to maintain session and cookies of the site using Axe-core?

### ISSUE THREAD

**Issue by syndy1989** [dequelabs/axe-webdriverjs#31]
Hi, I wanted to know how to maintain sessions and cookies in a user authenticated site using Axe-core? If Yes, How would i do that ? need to add any actions to the script or Is there any other way to do it?
Any advise on this would be helpful. Thanks in advance.

**Comment by dylanb** [comment]
yes, axe-webdriverjs builds on top of webdrive and it is definitely possible to set request headers in webdriver

http://stackoverflow.com/questions/10340373/how-to-send-cookies-with-selenium-webdriver
