### ISSUE TITLE
Content Security Policy issue in Chrome and Firefox

### ISSUE THREAD

**Issue by VivaGrendel** [dequelabs/axe-webdriverjs#35]
Hello I'm trying to make example below (taken from the project's README) work on my local machine but it does not produce any result:

```js
var AxeBuilder = require('axe-webdriverjs');
var WebDriver = require('selenium-webdriver');

var driver = new WebDriver.Builder()
  .forBrowser('firefox')
  .build();

driver
  .get('https://github.com/dequelabs/axe-webdriverjs')
  .then(function () {
    AxeBuilder(driver)
      .analyze(function (results) {
        console.log(results);
      });
  });
```

The browser is started and it navigates to the page but then, nothing.
Investigation in the web console of the started browser (Chrome) shows:

`Refused to execute inline script because it violates the following Content Security Policy directive: "script-src assets-cdn.github.com". Either the 'unsafe-inline' keyword, a hash ('sha256-XLagEkykG1v43U0BgF8iu7TAQJNjcpwT1QLNqImVlPk='), or a nonce ('nonce-...') is required to enable inline execution.`

From what I understand, you try to inject the axe js code directly inside a script tag. This does not comply with default security policies of modern browsers.

I could not find proper or clean ways to disable CSP in the browsers I need to test.

Am I missing something or is there any workaround?

**Comment by VivaGrendel** [comment]
I've just read issue #33. So the CSP issue is a known one. Does it mean axe-webdriverjs does not (yet?) on CSP enabled web sites?

**Comment by dylanb** [comment]
We are working on a fix for this. Closing due to duplicate.
