### ISSUE TITLE
AxeBuilder with a custom axe-core source not workin

### ISSUE THREAD

**Issue by aarontk** [dequelabs/axe-webdriverjs#38]
I'm trying to use AxeBuilder with a custom axe-core using the axeSource parameter as described on the axe-webdriverjs github page. It's not working. AxeBuilder is using the axe-core that was installed as pre-req for axe-webdriverjs. I have verified my axe-core is working by testing the page with axe-cli. I've also verified the axeSource string I'm passing is indeed the contents of the axe.min.js file.

**Comment by WilcoFiers** [comment]
Can you describe how what you've done is different from the unit test we have for this scenario:

https://github.com/dequelabs/axe-webdriverjs/blob/master/test/integration/doc-dylang.js

**Comment by aarontk** [comment]
It appears I should have triple checked. I tried it again, and I'm seeing the changes I expected. This can be closed. Sorry to have wasted your time.

**Comment by WilcoFiers** [comment]
Don't worry about it. Happy to help!
