### ISSUE TITLE
AxeBuilder configure is not a function error

### ISSUE THREAD

**Issue by singhsamyak** [dequelabs/axe-webdriverjs#39]
I have my AxeBuilder set up with Selenium and I can call functions like `analyze() ` and ` withTags()`. However, when I call`configure()`, I get the following error:

`Failed: (0, _axeWebdriverjs2.default)(...).configure is not a function`

I have it integrated with Jasmine and my code looks like this:
```
import AxeBuilder from "axe-webdriverjs";
import Selenium from "selenium-webdriver";

describe("Testing Button's accessibility", function() {
  var driver;

  beforeEach(function(done) {
    driver = new Selenium.Builder()
                .forBrowser('chrome')
                .build();

    driver.get('http://localhost:9010/index.html')
          .then(function() {
            done();
          });
  });

  afterEach(function(done) {
    driver.quit().then(function(){
      done();
    });
  });

  it('tests component against my set of rules', function (done) {
    var config = {
      'rules': {
        'id': 'angular-ng-click'
      }
    };
    AxeBuilder(driver)
      .configure(config)
      .analyze(function(results) {
        printViolations(results.violations, 'My Rules');
        expect (results.violations.length).toBe(0);
        done();
      });
  });

});

**Comment by marcysutton** [comment]
Can you provide your full test script so we can see how it is structured?

**Comment by singhsamyak** [comment]
@marcysutton I just updated my initial comment. Please refer to that!

**Comment by marcysutton** [comment]
Ah, my apologies–that rule doesn't exist. It was meant as an example. Have you tried running it with a valid config object?

**Comment by singhsamyak** [comment]
@marcysutton could you give me an example of a valid config object? I also ran it with
```
var config = {
   'rules': {
      'id': 'document-title'
   }
};
```
and got the same error.

**Comment by marcysutton** [comment]
Please review the axe-core documentation–it is linked in the paragraph above.

**Comment by singhsamyak** [comment]
@marcysutton I tried with a valid config object and the error persists.

**Comment by marcysutton** [comment]
Here's a better question: what are you hoping you achieve with configure? Are you trying to turn rules on or off, or override their behavior? Configure is meant to add new rules or modify existing rules, so without all the necessary pieces (documented in API.md) it won't be able to run.

**Comment by singhsamyak** [comment]
@marcysutton I'm trying to create a new rule that refers to an existing set of checks. 

I read through the API for checks and rules and came up with this config object...
```
    var my_check = {
      id: "invalidrole"
    };
    var my_rule = {
      id: "myRule",
      selector: ".mySelector",
      tags: ["best-practice"],
      metadata: {
        description: "ensures all nodes with 'mySelector' class has a valid role attribute",
        helpUrl: "http://foo.com",
        help: "add a valid role attribute"
      },
      all: [my_check]
    };
    var config = {
      reporter: "v2",
      checks: [my_check],
      rules: [my_rule]
    };
```
...which also results in the same error.

**Comment by marcysutton** [comment]
Here's an example using configure with a custom rule: https://github.com/dequelabs/axe-webdriverjs/blob/master/test/integration/doc-dylang.js

You could also test your custom rule with axe-core to make sure it works there.

**Comment by marcysutton** [comment]
Is there more to your custom rule? Because it's missing an evaluate function. I'm going to close this issue since `configure` works, this is more of a problem with the custom rule structure.

**Comment by singhsamyak** [comment]
@marcysutton I tried using the exact same [custom rule object](https://github.com/dequelabs/axe-webdriverjs/blob/master/test/integration/doc-dylang.js) and the same error persists.

**Comment by singhsamyak** [comment]
@marcysutton Additionally, I also did the following:

`console.log(typeof AxeBuilder(driver).analyze)` which returned 'function'
`console.log(typeof AxeBuilder(driver).configure)` which returned 'undefined'

**Comment by marcysutton** [comment]
Can you post your test script in its entirety so we can see it? I just got that rule to work in my demo axe-webdriverjs-demo project. https://github.com/marcysutton/axe-webdriverjs-demo

**Comment by singhsamyak** [comment]
```
import util from "util";
import AxeBuilder from "axe-webdriverjs";
import Selenium from "selenium-webdriver";

describe("Testing accessibility", function() {
  var driver;

  beforeEach(function(done) {
    driver = new Selenium.Builder()
                .forBrowser('chrome')
                .build();

    driver.get('http://localhost:9010/index.html')
          .then(function() {
            done();
          });
  });

  afterEach(function(done) {
    driver.quit().then(function(){
      done();
    });
  });

  /**
   * Prints accessibility test results to improve readability.
   * @param violations {array} caught by AXE-Core
   * @param conformance {string} label
   */
  function printViolations(violations, conformance) {
    console.log(`${conformance} Test Results`);
    console.log(`\x1b[31m${violations.length} total violation(s)\x1b[0m`);
    if (violations.length > 0) {
      violations.forEach(violation => {
        console.log('');
        console.log(`Impact      : ${violation.impact.toUpperCase()}`);
        console.log(`Violation   : ${violation.help}`);
        console.log(`Description : ${violation.description}`);
        var count = 1;
        violation.nodes.forEach(node => {
          console.log(`Node ${count}      : ${node.target}`);
          count++;
        });
      });
    }
  }

  /**
   * Catches all automatable violations from custom set of rules.
   */
  it('tests component against custom set of rules', function (done) {
    var config = {
       "checks": [
        {
         "id": "dylang",
         "options": ["dylan"],
         "evaluate": "function(){return true;}",
         "messages": {
          "pass": "Good language",
          "fail": "You mst use the DYLAN language"
         }
        }
       ],
       "rules": [
        {
         "id": "dylang",
         "metadata": {
          "description": "Ensures lang attributes have the value of 'dylan'",
          "help": "lang attribute must have the value of 'dylan'"
         },
         "selector": "html",
         "any": [],
         "all": [],
         "none": ["dylang"],
         "tags": ["wcag2aa"]
        }
       ],
       "data": {
        "rules": {
          "dylang": {
            "description": "Ensures lang attributes have the value of 'dylan'",
            "help": "lang attribute must have the value of 'dylan'"
          }
        }
       }
      };

    AxeBuilder(driver)
      .configure(config);
      .withRules(['dylang'])
      .analyze(function(results) {
        printViolations(results.violations, 'My Rules');
        expect (results.violations.length).toBe(0);
        done();
      });
  });

});
```

**Comment by marcysutton** [comment]
The chain of calls is broken here:
```
 AxeBuilder(driver)
      .configure(config);
      .withRules(['dylang'])
```
Remove the semicolon after `configure` to run the methods together. That made it work for me.

**Comment by singhsamyak** [comment]
@marcysutton Oops, I'm sorry, that was a typo while pasting the code here. Even without the semicolon the code doesn't work on my end :( 

I'm curious why typeof `configure` is `undefined` but `analyze` is a `function`

**Comment by marcysutton** [comment]
What version of axe-webdriverjs are you using? I get `function` when I run that log command.

**Comment by singhsamyak** [comment]
@marcysutton Update: just looked at my `axe-webdriverjs/lib/index.js` and `configure` is not defined. This is probably because I'm using `0.2.0`

Looks like the latest version is 1.1.1. I'll install that and try!

**Comment by singhsamyak** [comment]
@marcysutton Yup, the verdict was that my `package.json` had `^0.2.0` which never upgraded `axe-webdriverjs` to `1.x.x` causing `index.js` to never define `configure`.

Thank you so much for your time in responding to my comments!
