### ISSUE TITLE
Axe-core was removed from runtime dependencies

### ISSUE THREAD

**Issue by r33beers** [dequelabs/axe-webdriverjs#43]
https://github.com/dequelabs/axe-webdriverjs/commit/c5142e3eb79d83cbf5d98d8d4e669d848475db57 moves axe-core from `dependencies` to `devDependencies`, but `axe-core` is still referenced in the code. This causes failures with version 1.1.4.

**Comment by marcysutton** [comment]
Thanks so much for the heads up, that was not intentional. We'll replace it and do another release.

**Comment by marcysutton** [comment]
In the meantime, if you need to get unstuck you can install axe-core with `npm install axe-core` and require it in your tests. Or just stick with 1.1.3.

**Comment by marcysutton** [comment]
Fixed with 059d18d9081883a0dc3834776bd232df2b6459f7.
