### ISSUE TITLE
Uncaught exceptions in `lib/index.js`

### ISSUE THREAD

**Issue by zkf** [dequelabs/axe-webdriverjs#56]
In `lib/index.js`, there is missing a call to `.catch()` for the `driver.executeAsyncScript()` promise chain. When `executeAsyncScript` throws an exception, it is unhandled and will crash Node.

A fix seems to be to just tag `.catch(err => {reject(err)});` onto the `executeAsyncScript()` promise chain in `lib/index.js`.

**Comment by marcysutton** [comment]
IIRC we left that off so you wouldn't need a `catch` statement in your tests. But maybe @WilcoFiers remembers more about that.

**Comment by dennisreimann** [comment]
I ran into this as well. The error seems to occur as part of a race condition in case the driver is not instantiated per test, but reused across multiple tests.

> so you wouldn't need a catch statement in your tests

If so, axe should handle these errors internally and maybe log out a warning that i.e. the driver is not supposed to be reused. What are your thoughts on this?
