### ISSUE TITLE
What is the difference between this project and axe-selenium-java project? I'm trying to figure out a way to upgrade my axe-selenium project of v2.0.5 to axe v3.0 

### ISSUE THREAD

**Issue by rajudevjava** [dequelabs/axe-webdriverjs#57]

**Comment by marcysutton** [comment]
This project is for JavaScript (using Selenium Javascript bindings), and comes pre-bundled with axe-core@3.0.0. axe-selenium-java is for Java projects (using Selenium Java bindings), and it requires you to install axe-core separately. I don't think axe-selenium-java has been updated yet to work with 3.0. There's already an issue open to support it. https://github.com/dequelabs/axe-selenium-java/issues/15
