### ISSUE TITLE
Variation in the number of violations

### ISSUE THREAD

**Issue by rajudevjava** [dequelabs/axe-webdriverjs#59]
The number of violations are varying when aXe 3.0.0 s ran across the url and on the html content. I have taken the html content and saved it as test.html and gave the path of this file instead of url. 

       **browser.get('C:\\Users\\<.....>\\try_one.html').then(function () {
                     browser.executeAsyncScript(function(callback) {**

In the above case, violation are 6 and on the url - violation are 7. 
**Issues on URL:**
1.	Ensures the contrast between foreground and background colors meets WCAG 2 AA contrast ratio thresholds
2.	Ensures the order of headings is semantically correct
3.	Ensures every HTML document has a lang attribute
4.	Ensures <img> elements have alternate text or a role of none or presentation
5.	Ensures all content is contained within a landmark region
6.	Ensure all skip links have a focusable target
7.	**Ensures every form element has a label**

**Issues on html content from same url:**
1.	Ensures the contrast between foreground and background colors meets WCAG 2 AA contrast ratio thresholds
2.	Ensures the order of headings is semantically correct
3.	Ensures every HTML document has a lang attribute
4.	Ensures <img> elements have alternate text or a role of none or presentation
5.	Ensures all content is contained within a landmark region
6.	Ensure all skip links have a focusable target

Highlighted  is missing. Why is there a difference and how to handle it?

**Comment by straker** [comment]
It's hard to say without looking at it. It could be that 3rd party JavaScript is changing the DOM when at the url but not when saved to the file. If you could provide the URL in question I could take a look.

**Comment by straker** [comment]
Closing issue since we haven't gotten a response. Please open a new issue if this is still a problem.
