### ISSUE TITLE
Running a11y test in BrowserStack

### ISSUE THREAD

**Issue by tapanbasak** [dequelabs/axe-webdriverjs#6]
Hi **dylanb**....facing some issues while running accessibility test in BrowserStack.

1. If I run the test in andriod device, it is throwing below js exception -

> **javascript error: axe is not defined JavaScript stack: ReferenceError: axe is not defined at eval (eval at executeAsyncScript (unknown source), <anonymous>:4:5) at eval (eval at executeAsyncScript (unknown source), <anonymous>:5:7) at eval (eval at executeAsyncScript (unknown source), <anonymous>:5:33) at executeAsyncScript (<anonymous>:321:26) at <anonymous>:337:29 at callFunction (<anonymous>:229:33) at <anonymous>:239:23 at <anonymous>:240:3 at Object.InjectedScript._evaluateOn (<anonymous>:580:39) at Object.InjectedScript._evaluateAndWrap (<anonymous>:539:52) (Session info: webview=30.0.0.0) (Driver info: chromedriver=2.18.343837 (52eb4041461e46a6b73308ebb19e85787ced4281),platform=Mac OS X 10.10.5 x86_64) **

Whereas I can run a11y test successfully with firefox/chrome browser in window OS inside BrowserStack.

2. For some URLs, a11y test is not working in browserStack. It is showing below output -

> **messageSO_TIMEOUT**

What are the browsers & devices list on which I can run a11y test?

Thanks

**Comment by dylanb** [comment]
Can you share your test code?

**Comment by tapanbasak** [comment]
Hi **dylanb**..following is the test code -
```
var AxeBuilder = require('axe-webdriverjs'),
  WebDriver = require('selenium-webdriver');

// Input capabilities
var capabilities = {
  'browserName' : 'android',
  'platform' : 'ANDROID',
  'device' : 'Samsung Galaxy S5' ,
  'browserstack.user' : 'USERNAME',
  'browserstack.key' : 'ACCESSKEY',    
}

var driver = new WebDriver.Builder()
  .usingServer('http://hub.browserstack.com/wd/hub')
  .withCapabilities(capabilities)
  .usingWebDriverProxy("http://IP:PORT")
  .build();

driver
  .get('https://github.com/dequelabs/axe-webdriverjs')
  .then(function () {
    AxeBuilder(driver)
      .analyze(function (results) {
        console.log(results);
      });
  });
  driver.quit();
```
The above code is working fine with -

> var capabilities = {
>     'browserName' : 'firefox',
>     'browserstack.user' : 'USERNAME',
>     'browserstack.key' : 'ACCESSKEY', 
> }

Please let me know if you need any further details.

Thanks

**Comment by dylanb** [comment]
It looks like it is a timing-related issue.

Could you put some kind of call between these two lines

```
  .get('https://github.com/dequelabs/axe-webdriverjs')
  .then(function () {
```

That causes the Selenium driver to wait for the page to render?

Typical ways of doing this are:

1. Wait for the appearance of an element on the page (preferred),
1. Wait for a certain amount of time (still subject to timing, but more reliable)

Here is a (Java) article that talks about the different types of waits http://www.softwaretestinghelp.com/selenium-webdriver-waits-selenium-tutorial-15/

and

https://seleniumhq.github.io/selenium/docs/api/java/org/openqa/selenium/support/ui/ExpectedConditions.html

There are analogous calls in JavaScript, for example http://webdriver.io/api/utility/waitForExist.html

**Comment by marcysutton** [comment]
@tapanbasak is your issue still happening? I am going to close this due to inactivity; if the problem still persists, let us know!
