### ISSUE TITLE
What are the platforms this project supports? Would it work on Eclipse / NetBeans ? In NetBeans, I see an error under Selenium-webdriver module . Below is the screenshot. 

### ISSUE THREAD

**Issue by rajudevjava** [dequelabs/axe-webdriverjs#60]
![capture](https://user-images.githubusercontent.com/11168455/39652746-9d1d190e-4fbc-11e8-8dbc-9ad1d57c674e.PNG)

**Comment by marcysutton** [comment]
This project requires Node.js, and does not support Java IDEs. It won't work in Eclipse or Netbeans. Try a text editor that supports JavaScript projects, like VS Code or Sublime Text.
