### ISSUE TITLE
Module objects cannot be functions (should use a named export)

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [dequelabs/axe-webdriverjs#74]
This is not valid JavaScript:

```javascript
import * as AxeBuilder from "axe-webdriverjs";

AxeBuilder(browser);
```

See [this SO answer](https://stackoverflow.com/a/39415662/1830407):

> An ES6 module namespace object cannot be invoked as a function or with new.

...so what should happen instead is:

```javascript
import { AxeBuilder } from "axe-webdriverjs";

AxeBuilder(browser);
```

🙃.

Fortunately, this can be a purely additive change: somewhere in `lib/index.js`, you can add:

```javascript
AxeBuilder.AxeBuilder = AxeBuilder;
```

...so that both the CommonJS-style `const AxeBuilder = require("axe-webdriverjs");` and ES-style above or `const AxeBuilder = require("axe-webdriverjs").AxeBuilder;` will work.

**Comment by stephenmathieson** [comment]
I think I'm missing context here. Why are you importing this package that way?

**Comment by JoshuaKGoldberg** [comment]
@stephenmathieson sorry, I don't follow your question. Are you wondering why I'm importing the module like `import { AxeBuilder } from "axe-webdriverjs"` instead of `import * as AxeBuilder from "axe-webdriverjs"`? If that's what you intend to ask, it's because the spec for modules explicitly doesn't allow it. An ES6 module namespace object cannot be invoked as a function or with new.
