### ISSUE TITLE
Stumped by install problems.

### ISSUE THREAD

**Issue by mgifford** [dequelabs/axe-webdriverjs#82]
Would love some direction. 

$ npm install selenium-webdriver 
npm WARN axe-webdriverjs@2.0.1 requires a peer of selenium-webdriver@>= 2.53.1 but none is installed. You must install peer dependencies yourself.

+ selenium-webdriver@4.0.0-alpha.1
updated 1 package and audited 1269 packages in 6.201s
found 6 vulnerabilities (1 low, 4 high, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details

$ npm install axe-webdriverjs
npm WARN axe-webdriverjs@2.0.1 requires a peer of selenium-webdriver@>= 2.53.1 but none is installed. You must install peer dependencies yourself.

+ axe-webdriverjs@2.0.1
updated 1 package and audited 1269 packages in 3.186s
found 6 vulnerabilities (1 low, 4 high, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details

**Comment by marcysutton** [comment]
Hi Mike, for now you can get around that by updating to a newer version of Selenium Webdriver. The `npm audit` suggested version 3.6.0 as being without vulnerabilities:

``` npm install selenium-webdriver@3.6.0```

Package.json has this in its dependencies: `"selenium-webdriver": ">= 2.53.1"`. @WilcoFiers should we update that to 3.6.0 or later?

**Comment by mgifford** [comment]
That didn't seem to do much different:

$ npm install selenium-webdriver
+ selenium-webdriver@3.6.0
updated 1 package and audited 1269 packages in 3.963s
found 6 vulnerabilities (1 low, 4 high, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details

$  npm install selenium-webdriver@3.6.0
+ selenium-webdriver@3.6.0
updated 1 package and audited 1269 packages in 2.957s
found 6 vulnerabilities (1 low, 4 high, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details

Although I don't understand the "+ selenium-webdriver@3.6.0" in either:

In looking in the  /usr/local/lib/node_modules/axe-cli/node_modules/axe-webdriverjs/package.json I found:
    "selenium-webdriver": "^3.6.0",

**Comment by marcysutton** [comment]
You should try running `npm audit fix` and see what it suggests for you. Ultimately we might need to pin a newer version of Selenium Webdriver into package.json, but 3.6.0 worked for me so I'm not sure the best version would be quite yet.

**Comment by mgifford** [comment]
I think I got through that point by doing a: npm audit fix --force

I don't know enough to fix anything here manually.

So "it works now", but I still haven't gotten it to do anything useful.

It would be amazing if the documentation gave more details.  

So within the Usage tab, what should the file be named? How do I execute it?  I'm missing something more primitive here. 

With a lot of the other similar scripts I could execute a crawl from the command line. I understand this is different, but need more documentation.

Thanks!

**Comment by marcysutton** [comment]
Your test file(s) can be arbitrarily named whatever you like. You can kick them off with the `npm test` command by hooking up your tests in the `scripts` section of package.json. This demo might be useful, it uses Jasmine as the test runner to point to a test file in the `spec` directory: https://github.com/marcysutton/axe-webdriverjs-demo

**Comment by marcysutton** [comment]
@mgifford what versions of Node and npm are you using? I'm on Node 9 and npm 6.4.1, and everything installs fine for me. What errors are you seeing?

One thing I noticed is the spec demo I linked above requires Selenium-Webdriver 3x, as it hasn't been updated for the new 4x APIs.

**Comment by mgifford** [comment]
I blew it all away and started fresh with:
https://nodejs.org/en/

node = v10.13.0
npm  = v6.4.1

Now it seems to have no problem installing either selenium-webdriver or axe-webdriverjs so I am going to close this comment.  Thanks!

I still have to get to the testing with https://github.com/marcysutton/axe-webdriverjs-demo but I am closer.
