### ISSUE TITLE
Error must be handled as the first argument of axe.analyze

### ISSUE THREAD

**Issue by luarmr** [dequelabs/axe-webdriverjs#92]
It will be great to update this example since is linked from the readme and It will be removed in the next major release.

https://github.com/dequelabs/axe-webdriverjs/blob/05d832cbaf8a53e36c47b56b427de30052c783e2/test/sauce/sauce.js#L31

```
AxeBuilder(driver)
  .analyze(function(err, results) {
    if (err) {
      // Handle error somehow
    }
      assert.equal(results.url, url);
      done();
  });
```

**Comment by stephenmathieson** [comment]
Whoops, missed that in #83.

Feel free to open a PR. Otherwise I'll update the example within a day or so.
